trigger:
- master

variables:
- name: workspace_publish_branch
  value: 'workspace_publish'

stages:
- stage: Deploy
  displayName: 'Deploy to Azure'
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Azure'
    environment: 'QA' # Replace with the name of your environment
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: DownloadGitHubAction@0
            inputs:
              repository: 'PromitXI/Synapse-dev'
              ref: '$(workspace_publish_branch)' # Use the value of the workspace_publish_branch variable
              path: '$(System.DefaultWorkingDirectory)/workspace_publish'
            displayName: 'Download GitHub Action'
          
          - task: SynapseWorkspaceDeployment@0
            inputs:
              ConnectedServiceName: 'ServeConnPipeline'
              FolderPath: '$(System.DefaultWorkingDirectory)/workspace_publish/synapse-data-dev-van'
              ArtifactsLocation: '$(System.DefaultWorkingDirectory)/workspace_publish/synapse-data-dev-van'
              TemplateLocation: 'Linked artifact'
              LinkedTemplateFilePath: 'template.json'
              LinkedParametersFilePath: 'parameters.json'
              DeploymentMode: 'Incremental'