trigger:
- master

variables:
- name: workspace_publish_branch
  value: 'workspace_publish'

stages:
- stage: Deploy
  displayName: 'Deploy to Azure'
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Azure'
    environment: 'QA' # Replace with the name of your environment
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: DownloadGitHubAction@1
            inputs:
              repository: 'PromitXI/Synapse-dev'
              ref: '$(workspace_publish_branch)' # Use the value of the workspace_publish_branch variable
              path: '$(System.DefaultWorkingDirectory)/workspace_publish'
            displayName: 'Download GitHub Action'
          
          - task: Synapse workspace deployment@1
            inputs:
              
              azureSubscription: '58a3cb06-91b3-4f09-82b8-882ec0a9c038'
              
              TargetWorkspaceName: 'synapse-qa-van' # Replace with the name of your Synapse workspace
              ResourceGroupName: 'RG-PWB-Test-DataPlatform-westus3' # Replace with the name of the resource group where your Synapse workspace is located
              TemplateFile: '$(System.DefaultWorkingDirectory)/workspace_publish/synapse-data-dev-van/template.json'
              ParametersFile: '$(System.DefaultWorkingDirectory)/workspace_publish/synapse-data-dev-van/parameters.json'
              