trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest



variables:
  workspace: 'synapse-$(env)-van'
  system.debug: true

steps:

# - task: Approval@1
#   displayName: 'Approval For Deployment'
#   inputs:
#     approvers: 'promit.xi@gmail.com,promitazure@gmail.com'
#     timeoutInMinutes: '1440'
  
- task: Synapse workspace deployment@2
  inputs:
    operation: 'validateDeploy'
    ArtifactsFolder: 'synapse-data-dev-van'
    azureSubscription: 'Promit''s Cloud (58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-PWB-Test-DataPlatform-westus3'
    TargetWorkspaceName: 'synapse-qa-van'
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    OverrideArmParameters: '-workspaceName $(workspace)'
    FailOnMissingOverrides: false
    Environment: 'prod'
    npmpackage: 'prod'


  

# steps:
# - task: AzureSynapseWorkspace.synapsecicd-deploy.synapse-deploy.Synapse workspace deployment@2
#   displayName: 'Synpase deployment task for workspace: synapse-$(env)-van'
#   inputs:
#     TemplateFile: '$(System.DefaultWorkingDirectory)/_PromitXI_Synapse-dev/synapse-data-dev-van/TemplateForWorkspace.json'
#     ParametersFile: '$(System.DefaultWorkingDirectory)/_PromitXI_Synapse-dev/synapse-data-dev-van/TemplateParametersForWorkspace.json'
#     azureSubscription: 'Promit''s Cloud (58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
#     ResourceGroupName: 'RG-PWB-Test-DataPlatform-westus3'
#     TargetWorkspaceName: 'synapse-$(env)-van'
#     OverrideArmParameters: '-workspaceName $(workspace)'
