# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Synapse workspace deployment@2
  inputs:
    operation: 'validateDeploy'
    ArtifactsFolder: 'synapse-data-dev-van'
    azureSubscription: 'Promit''s Cloud(2)(58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-PWB-Test-DataPlatform-westus3'
    TargetWorkspaceName: 'synapse-qa-van'
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    FailOnMissingOverrides: false
    Environment: 'prod'
    npmpackage: 'prod'
