# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureSynapseWorkspace.synapsecicd-deploy.synapse-deploy.Synapse workspace deployment@2
  displayName: 'Synpase deployment task for workspace: synapse-qa-van'
  inputs:
    TemplateFile: '$(System.DefaultWorkingDirectory)/_PromitXI_Synapse-dev/synapse-data-dev-van/TemplateForWorkspace.json'
    ParametersFile: '$(System.DefaultWorkingDirectory)/_PromitXI_Synapse-dev/synapse-data-dev-van/TemplateParametersForWorkspace.json'
    azureSubscription: 'Promit''s Cloud (58a3cb06-91b3-4f09-82b8-882ec0a9c038)'
    ResourceGroupName: 'RG-PWB-Test-DataPlatform-westus3'
    TargetWorkspaceName: 'synapse-qa-van'