trigger:
- main


  

pool:
  vmImage: 'windows-latest'

variables:
  system.debug: true
  resourceGroupName: 'RG-PWB-Test-DataPlatform-westus3'
  synapseWorkspaceName: 'synapse-qa-van'
  synapseArtifactFolder: 'synapse-data-dev-van'
  githubRepo: 'https://github.com/PromitXI/Synapse-dev'
  githubBranch: 'workspace_publish'
  githubToken: $(GITHUB_TOKEN)

steps:
- task: DownloadSecureFile@1
  displayName: 'Download GitHub token'
  inputs:
    secureFile: 'Github-Token.txt'
  env:
    GITHUB_TOKEN: $(DownloadSecureFile.secureFilePath)

- task: GitClone@2
  displayName: 'Clone repository'
  inputs:
    RepositoryURL: 'https://github.com/PromitXI/Synapse-dev'
    repository: '$(githubRepo)'
    branch: '$(githubBranch)'
    clean: true
    auth: 'OAuth'
    token: $(githubToken)

- task: Synapse workspace deployment@1
  displayName: 'Deploy to Synapse Workspace'
  inputs:
    ConnectedServiceName: 'MySynapseServiceConnection'
    ResourceGroupName: $(resourceGroupName)
    WorkspaceName: $(synapseWorkspaceName)
    ArtifactFolder: $(synapseArtifactFolder)
    TemplateFile: 'Template.json'
    ParametersFile: 'parameter.json'
